
version: '2.17.2'

services:

    agario-ros:
        image: agario-ros
        container_name: agario-ros
        networks:
            - ros-tutorial-network
        build:
            context: .
            dockerfile: ./dockerfile
            target: base
        volumes:
          - ./../agario_ros:/workspace/src/agario_ros
          # - ./../src:/workspace/src

        environment:
            - "DISPLAY=novnc:0.0"


networks:
    ros-tutorial-network:
        name: ros-tutorial-network
        driver: bridge
        external: true
